### ISSUE TITLE
sVim link hints don't work with Nightlight Safari extension

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#101]
I am using [Nightlight](https://itunes.apple.com/nl/app/nightlight-for-safari/id1429386865?l=en&mt=12) Safari extension to automatically turn all the websites I visit into dark mode as I just downloaded Mojawe and love its night mode.

However with it, sVim link hints become unusable as you can't read the letters any more. Here is how it looks:

![2018-09-25 at 00 52](https://user-images.githubusercontent.com/6391776/45983560-5415b380-c05d-11e8-919b-a1424b580d5b.png)

Is it possible to fix this?

**Comment by luchenyuxx** [comment]
@nikitavoloboev you can change your hint style in the settings. Change it to another colour if the current one is not visible.
```
.sVim-hint {
  background-color: #FFFF01;
  color: #000000;
  font-size: 10pt;
  font-family: monospace;
  line-height: 10pt;
  padding: 0px;
  opacity: 0.7;
  position: fixed;
}
```

**Comment by abrookins** [comment]
I haven't played with that extension, but you might also try something like
Stylus (or Stylish) to apply a setting that changes the sVim CSS highlight
based on the presence of some a class applied to the document when that
plugin is active (assuming it applies some style like that). Or else find a
hint style that you can use in your sVim settings that works well both
light and dark -- though that sounds hard.

As for building an integration point with that plugin into sVim, that would
put us in a position to keep track of any breaking changes that plugin
makes and probably isn't something I can get on board with.

**Comment by nikitavoloboev** [comment]
I used @luchenyuxx advice and changed my .sVim-hint CSS to this:

```css

.sVim-hint {
 /* background-color: #FFFF01; white */
  background-color: ##FFFFF8; /* night */
 /* color: #000000;  white */
  color: #EBEBEB; /* night */
  font-size: 10pt; 
  font-family: monospace;
  line-height: 10pt;
  padding: 0px;
  opacity: 0.7;
}
```

It works well only in some cases I get purple background like here 
![2018-09-27 at 00 42](https://user-images.githubusercontent.com/6391776/46113341-4b081c00-c1ee-11e8-85ab-d08ed3e16c60.png)

Anyone knows why?
